main:
  task: "classification"

dataset:
  train:
    root: "D:/projects/data/image_classification/Intel_Image_Classification/seg_train/seg_train"
    transforms:
      input: "standard_tf"
    batch_size: 32
    additional_params:
      img_size: 64
      mean: (0.5, 0.5, 0.5)
      std: (0.5, 0.5, 0.5)
      p: 0.5
  val:
    root: "D:/projects/data/image_classification/Intel_Image_Classification/seg_train/seg_val"
    transforms:
      input: "standard_tf"
    batch_size: 32
    additional_params:
      img_size: 64
      mean: (0.5, 0.5, 0.5)
      std: (0.5, 0.5, 0.5)
      p: 0.5
  test:
    root: "D:/projects/data/image_classification/Intel_Image_Classification/seg_test/seg_test"
    transforms:
      input: "standard_tf"
    batch_size: 32
    additional_params:
      img_size: 64
      mean: (0.5, 0.5, 0.5)
      std: (0.5, 0.5, 0.5)
      p: 0.5

model:
  type: VGG19
  classifier:
    type: VGGClassifier
    params:
      num_classes: 10
  metric: Accuracy

loss:
  type: CrossEntropyLoss
