main:
  task: "name of task"

dataset:
  train:
    root: "path to dataset"
    transforms:
      input: "name of transforms for input data"
      gt: "name of transforms for ground truth"
    batch_size: 32
  val:
    root: "path to dataset"
    transforms:
      input: "name of transforms for input data"
      gt: "name of transforms for ground truth"
    batch_size: 32
  test:
    root: "path to dataset"
    transforms:
      input: "name of transforms for input data"
      gt: "name of transforms for ground truth"
    batch_size: 32
